version: "3.8"

services:
  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    container_name: jenkins-controller
    restart: unless-stopped
    privileged: true
    user: root
    ports:
      - "8080:8080" # Interface web Jenkins
      - "50000:50000" # Port pour les agents JNLP
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # donne les clefs de docker a jenkins
      - ./../:/workspace:Z
      - ./jenkins/casc.yml:/var/jenkins_home/casc.yml:ro # pour creer des trucs au lancement grace au plugin configuration-as-code
    environment:
      - JENKINS_ADMIN_ID=admin
      - JENKINS_ADMIN_PASSWORD=admin123
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false -Dhudson.security.csrf.GlobalCrumbIssuerConfiguration.DISABLE_CSRF_PROTECTION=true
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc.yml
    networks:
      - jenkins-network

  jenkins-agent-linux:
    build:
      context: ./agents/linux
      dockerfile: Dockerfile
    container_name: jenkins-agent-linux
    restart: unless-stopped
    depends_on:
      - jenkins
      - mysql
    environment:
      - JENKINS_URL=http://jenkins-controller:8080
      - AGENT_NAME=linux-agent
      - AGENT_WORKDIR=/home/jenkins/agent
    networks:
      - jenkins-network

  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile.mysql
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bibliotheque
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - jenkins-network

volumes:
  jenkins-data:
  mysql-data:
  agent-workdir:

networks:
  jenkins-network:
    driver: bridge
