version: "3.8"

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins-controller
    restart: unless-stopped
    privileged: true
    user: root
    ports:
      - "8080:8080" # Interface web Jenkins
      - "50000:50000" # Port pour les agents JNLP
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./../../:/workspace:Z
    environment:
      - JENKINS_ADMIN_ID=admin
      - JENKINS_ADMIN_PASSWORD=admin123
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false -Dhudson.security.csrf.GlobalCrumbIssuerConfiguration.DISABLE_CSRF_PROTECTION=true
    networks:
      - jenkins-network

  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bibliotheque
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - jenkins-network
    # j'ai eu des problÃ¨me d'espace a des moments, je ne sais pas si cette commande est encore utile
    command: >
      --default-authentication-plugin=mysql_native_password
      --innodb-use-native-aio=0
      --innodb-flush-method=fsync
      --innodb-log-file-size=5M
      --innodb-buffer-pool-size=64M

  jenkins-agent-linux:
    build:
      context: ../agents/linux
      dockerfile: Dockerfile
    container_name: jenkins-agent-linux
    restart: unless-stopped
    depends_on:
      - jenkins
      - mysql
    volumes:
      - ./../../:/workspace:Z
      - agent-workdir:/home/jenkins/agent
    environment:
      - JENKINS_URL=http://jenkins-controller:8080
    networks:
      - jenkins-network
    # On laisse le conteneur tourner pour connexion manuelle

volumes:
  jenkins-data:
  mysql-data:
  agent-workdir:

networks:
  jenkins-network:
    driver: bridge
